# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pmontiel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/01 16:35:21 by pmontiel          #+#    #+#              #
#    Updated: 2022/03/18 13:28:47 by pmontiel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: '3'
services:
    nginx:
        container_name: "nginx_cont"
        build: ./requirements/nginx
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - wordpress
        networks:
            - incep
        ports:
              - 443:443
        restart: always
    wordpress:
        image: wordpress
        container_name: "wordpress_cont"
        build: ./requirements/wordpress
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - db
        networks:
            - incep
        environment:
            - WORDPRESS_DB_HOST:db:3306
            - MYSQL_ROOT_PASSWORD:mysql_root_pass
            - WORDPRESS_DB_NAME:db_name
            - WORDPRESS_DB_USER:user_name
            - WORDPRESS_DB_PASSWORD:user_pass
            - WORDPRESS_TABLE_PREFIX:wp_
        restart: always
    db:
        image: "mariadb:${MARIADB_VERSION}"
        build: ./requirements/mariadb
        ports:
            - 3306:3306
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - incep
        environment:
            - MYSQL_ROOT_PASSWORD:mysql_root_pass
            - MYSQL_DATABASE:db_name
            - MYSQL_USER:user_name
            - MYSQL_PASSWORD:user_passnetworks
        restart: always
networks:
    incep:
volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            device: "/Users/pmontiel/Documents/word"
            o: bind
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            device: "/Users/pmontiel/Documents/mari"
            o: bind
